/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AuditLog {
  export type AuditEntryStruct = {
    id: BigNumberish;
    eventType: BigNumberish;
    actorId: string;
    targetId: string;
    barangayId: string;
    dataHash: BytesLike;
    metadata: string;
    timestamp: BigNumberish;
  };

  export type AuditEntryStructOutput = [
    id: bigint,
    eventType: bigint,
    actorId: string,
    targetId: string,
    barangayId: string,
    dataHash: string,
    metadata: string,
    timestamp: bigint
  ] & {
    id: bigint;
    eventType: bigint;
    actorId: string;
    targetId: string;
    barangayId: string;
    dataHash: string;
    metadata: string;
    timestamp: bigint;
  };
}

export interface AuditLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EVT_APPT_BOOKED"
      | "EVT_APPT_COMPLETED"
      | "EVT_QR_SCAN_DENIED"
      | "EVT_QR_SCAN_GRANTED"
      | "EVT_RECORD_CREATED"
      | "EVT_RECORD_UPDATED"
      | "EVT_REFERRAL_ACCEPTED"
      | "EVT_REFERRAL_CREATED"
      | "EVT_REFERRAL_REJECTED"
      | "getEntries"
      | "getEntry"
      | "logEvent"
      | "owner"
      | "totalEntries"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Logged"): EventFragment;

  encodeFunctionData(
    functionFragment: "EVT_APPT_BOOKED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVT_APPT_COMPLETED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVT_QR_SCAN_DENIED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVT_QR_SCAN_GRANTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVT_RECORD_CREATED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVT_RECORD_UPDATED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVT_REFERRAL_ACCEPTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVT_REFERRAL_CREATED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVT_REFERRAL_REJECTED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logEvent",
    values: [BigNumberish, string, string, string, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalEntries",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "EVT_APPT_BOOKED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVT_APPT_COMPLETED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVT_QR_SCAN_DENIED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVT_QR_SCAN_GRANTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVT_RECORD_CREATED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVT_RECORD_UPDATED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVT_REFERRAL_ACCEPTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVT_REFERRAL_CREATED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVT_REFERRAL_REJECTED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logEvent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalEntries",
    data: BytesLike
  ): Result;
}

export namespace LoggedEvent {
  export type InputTuple = [
    id: BigNumberish,
    eventType: BigNumberish,
    actorId: string,
    targetId: string,
    barangayId: string,
    dataHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    eventType: bigint,
    actorId: string,
    targetId: string,
    barangayId: string,
    dataHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    eventType: bigint;
    actorId: string;
    targetId: string;
    barangayId: string;
    dataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditLog extends BaseContract {
  connect(runner?: ContractRunner | null): AuditLog;
  waitForDeployment(): Promise<this>;

  interface: AuditLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EVT_APPT_BOOKED: TypedContractMethod<[], [bigint], "view">;

  EVT_APPT_COMPLETED: TypedContractMethod<[], [bigint], "view">;

  EVT_QR_SCAN_DENIED: TypedContractMethod<[], [bigint], "view">;

  EVT_QR_SCAN_GRANTED: TypedContractMethod<[], [bigint], "view">;

  EVT_RECORD_CREATED: TypedContractMethod<[], [bigint], "view">;

  EVT_RECORD_UPDATED: TypedContractMethod<[], [bigint], "view">;

  EVT_REFERRAL_ACCEPTED: TypedContractMethod<[], [bigint], "view">;

  EVT_REFERRAL_CREATED: TypedContractMethod<[], [bigint], "view">;

  EVT_REFERRAL_REJECTED: TypedContractMethod<[], [bigint], "view">;

  getEntries: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [AuditLog.AuditEntryStructOutput[]],
    "view"
  >;

  getEntry: TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint] & {
        eventType: bigint;
        actorId: string;
        targetId: string;
        barangayId: string;
        dataHash: string;
        metadata: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  logEvent: TypedContractMethod<
    [
      eventType: BigNumberish,
      actorId: string,
      targetId: string,
      barangayId: string,
      dataHash: BytesLike,
      metadata: string
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  totalEntries: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EVT_APPT_BOOKED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVT_APPT_COMPLETED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVT_QR_SCAN_DENIED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVT_QR_SCAN_GRANTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVT_RECORD_CREATED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVT_RECORD_UPDATED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVT_REFERRAL_ACCEPTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVT_REFERRAL_CREATED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVT_REFERRAL_REJECTED"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEntries"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [AuditLog.AuditEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint] & {
        eventType: bigint;
        actorId: string;
        targetId: string;
        barangayId: string;
        dataHash: string;
        metadata: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "logEvent"
  ): TypedContractMethod<
    [
      eventType: BigNumberish,
      actorId: string,
      targetId: string,
      barangayId: string,
      dataHash: BytesLike,
      metadata: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalEntries"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Logged"
  ): TypedContractEvent<
    LoggedEvent.InputTuple,
    LoggedEvent.OutputTuple,
    LoggedEvent.OutputObject
  >;

  filters: {
    "Logged(uint256,uint8,string,string,string,bytes32,uint256)": TypedContractEvent<
      LoggedEvent.InputTuple,
      LoggedEvent.OutputTuple,
      LoggedEvent.OutputObject
    >;
    Logged: TypedContractEvent<
      LoggedEvent.InputTuple,
      LoggedEvent.OutputTuple,
      LoggedEvent.OutputObject
    >;
  };
}
