/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HealthRecordRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorRecord"
      | "getLatestRecord"
      | "getRecord"
      | "getRecordCount"
      | "owner"
      | "revokeRecord"
      | "verifyHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RecordAnchored" | "RecordRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorRecord",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestRecord",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeRecord",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHash",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyHash", data: BytesLike): Result;
}

export namespace RecordAnchoredEvent {
  export type InputTuple = [
    residentId: string,
    recordHash: BytesLike,
    recordType: string,
    timestamp: BigNumberish,
    anchoredBy: AddressLike
  ];
  export type OutputTuple = [
    residentId: string,
    recordHash: string,
    recordType: string,
    timestamp: bigint,
    anchoredBy: string
  ];
  export interface OutputObject {
    residentId: string;
    recordHash: string;
    recordType: string;
    timestamp: bigint;
    anchoredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordRevokedEvent {
  export type InputTuple = [
    residentId: string,
    recordHash: BytesLike,
    timestamp: BigNumberish,
    revokedBy: AddressLike
  ];
  export type OutputTuple = [
    residentId: string,
    recordHash: string,
    timestamp: bigint,
    revokedBy: string
  ];
  export interface OutputObject {
    residentId: string;
    recordHash: string;
    timestamp: bigint;
    revokedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthRecordRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HealthRecordRegistry;
  waitForDeployment(): Promise<this>;

  interface: HealthRecordRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorRecord: TypedContractMethod<
    [residentId: string, recordHash: BytesLike, recordType: string],
    [void],
    "nonpayable"
  >;

  getLatestRecord: TypedContractMethod<
    [residentId: string, recordType: string],
    [[string, bigint] & { latestHash: string; latestTimestamp: bigint }],
    "view"
  >;

  getRecord: TypedContractMethod<
    [residentId: string, index: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        hash: string;
        recordType: string;
        timestamp: bigint;
        anchoredBy: string;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getRecordCount: TypedContractMethod<[residentId: string], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  revokeRecord: TypedContractMethod<
    [residentId: string, index: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyHash: TypedContractMethod<
    [recordHash: BytesLike],
    [[boolean, boolean] & { exists: boolean; revoked: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorRecord"
  ): TypedContractMethod<
    [residentId: string, recordHash: BytesLike, recordType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getLatestRecord"
  ): TypedContractMethod<
    [residentId: string, recordType: string],
    [[string, bigint] & { latestHash: string; latestTimestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [residentId: string, index: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        hash: string;
        recordType: string;
        timestamp: bigint;
        anchoredBy: string;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordCount"
  ): TypedContractMethod<[residentId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeRecord"
  ): TypedContractMethod<
    [residentId: string, index: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyHash"
  ): TypedContractMethod<
    [recordHash: BytesLike],
    [[boolean, boolean] & { exists: boolean; revoked: boolean }],
    "view"
  >;

  getEvent(
    key: "RecordAnchored"
  ): TypedContractEvent<
    RecordAnchoredEvent.InputTuple,
    RecordAnchoredEvent.OutputTuple,
    RecordAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "RecordRevoked"
  ): TypedContractEvent<
    RecordRevokedEvent.InputTuple,
    RecordRevokedEvent.OutputTuple,
    RecordRevokedEvent.OutputObject
  >;

  filters: {
    "RecordAnchored(string,bytes32,string,uint256,address)": TypedContractEvent<
      RecordAnchoredEvent.InputTuple,
      RecordAnchoredEvent.OutputTuple,
      RecordAnchoredEvent.OutputObject
    >;
    RecordAnchored: TypedContractEvent<
      RecordAnchoredEvent.InputTuple,
      RecordAnchoredEvent.OutputTuple,
      RecordAnchoredEvent.OutputObject
    >;

    "RecordRevoked(string,bytes32,uint256,address)": TypedContractEvent<
      RecordRevokedEvent.InputTuple,
      RecordRevokedEvent.OutputTuple,
      RecordRevokedEvent.OutputObject
    >;
    RecordRevoked: TypedContractEvent<
      RecordRevokedEvent.InputTuple,
      RecordRevokedEvent.OutputTuple,
      RecordRevokedEvent.OutputObject
    >;
  };
}
