/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuditLog } from "./AuditLog";
export type { HealthRecordRegistry } from "./HealthRecordRegistry";
export * as factories from "./factories";
export { AuditLog__factory } from "./factories/AuditLog__factory";
export { HealthRecordRegistry__factory } from "./factories/HealthRecordRegistry__factory";
